// Dictionnaire Wolof-Français-Anglais
const dictionnaire = [
    { wolof: "salaam aleekum", francais: "bonjour (salutation islamique)", anglais: "hello (Islamic greeting)" },
    { wolof: "na nga def", francais: "comment vas-tu", anglais: "how are you" },
    { wolof: "maangi fi", francais: "je vais bien", anglais: "I'm fine" },
    { wolof: "jërejëf", francais: "merci", anglais: "thank you" },
    { wolof: "waaw", francais: "oui", anglais: "yes" },
    { wolof: "déedéet", francais: "non", anglais: "no" },
    { wolof: "ba beneen", francais: "à bientôt", anglais: "see you soon" },
    { wolof: "ci jamm", francais: "au revoir", anglais: "goodbye" },
    { wolof: "nit", francais: "personne", anglais: "person" },
    { wolof: "jigéen", francais: "femme", anglais: "woman" },
    { wolof: "góor", francais: "homme", anglais: "man" },
    { wolof: "xale", francais: "enfant", anglais: "child" },
    { wolof: "mag", francais: "frère/sœur aîné(e)", anglais: "older brother/sister" },
    { wolof: "rakk", francais: "frère/sœur cadet(te)", anglais: "younger brother/sister" },
    { wolof: "ndey", francais: "mère", anglais: "mother" },
    { wolof: "baay", francais: "père", anglais: "father" },
    { wolof: "lëk", francais: "manger", anglais: "to eat" },
    { wolof: "naan", francais: "boire", anglais: "to drink" },
    { wolof: "dellu", francais: "retourner", anglais: "to return" },
    { wolof: "dem", francais: "aller", anglais: "to go" },
    { wolof: "jàng", francais: "étudier", anglais: "to study" },
    { wolof: "liggéey", francais: "travailler", anglais: "to work" },
    { wolof: "togg", francais: "cuisiner", anglais: "to cook" },
    { wolof: "xool", francais: "regarder", anglais: "to look" },
    { wolof: "dégg", francais: "écouter", anglais: "to listen" },
    { wolof: "wax", francais: "parler", anglais: "to speak" },
    { wolof: "gëm", francais: "croire", anglais: "to believe" },
    { wolof: "xam", francais: "savoir", anglais: "to know" },
    { wolof: "bes", francais: "suffire", anglais: "to be enough" },
    { wolof: "bëgg", francais: "aimer", anglais: "to love" },
    { wolof: "sopp", francais: "détester", anglais: "to hate" },
    { wolof: "génn", francais: "sortir", anglais: "to go out" },
    { wolof: "dëkk", francais: "habiter", anglais: "to live (reside)" },
    { wolof: "dëgg", francais: "vérité", anglais: "truth" },
    { wolof: "dollar", francais: "argent", anglais: "money" },
    { wolof: "kër", francais: "maison", anglais: "house" },
    { wolof: "neeg", francais: "mariage", anglais: "wedding" },
    { wolof: "jàng", francais: "école", anglais: "school" },
    { wolof: "tëre", francais: "livre", anglais: "book" },
    { wolof: "kayit", francais: "papier", anglais: "paper" },
    { wolof: "bunt", francais: "porte", anglais: "door" },
    { wolof: "palanteer", francais: "fenêtre", anglais: "window" },
    { wolof: "kangu", francais: "chaise", anglais: "chair" },
    { wolof: "tabël", francais: "table", anglais: "table" },
    { wolof: "lal", francais: "lit", anglais: "bed" },
    { wolof: "mbët", francais: "vêtement", anglais: "clothing" },
    { wolof: "sapato", francais: "chaussure", anglais: "shoe" },
    { wolof: "njar", francais: "pluie", anglais: "rain" },
    { wolof: "ndox", francais: "eau", anglais: "water" },
    { wolof: "safara", francais: "nourriture", anglais: "food" },
    { wolof: "ceeb", francais: "riz", anglais: "rice" },
    { wolof: "mburu", francais: "pain", anglais: "bread" },
    { wolof: "meew", francais: "poisson", anglais: "fish" },
    { wolof: "yapp", francais: "viande", anglais: "meat" },
    { wolof: "weñ", francais: "arachide", anglais: "peanut" },
    { wolof: "fonde", francais: "maïs", anglais: "corn" },
    { wolof: "bant", francais: "sel", anglais: "salt" },
    { wolof: "suukër", francais: "sucre", anglais: "sugar" },
    { wolof: "nettali", francais: "thé", anglais: "tea" },
    { wolof: "kafe", francais: "café", anglais: "coffee" },
    { wolof: "dinaar", francais: "repas", anglais: "meal" },
    { wolof: "tangan", francais: "faim", anglais: "hunger" },
    { wolof: "mar", francais: "soif", anglais: "thirst" },
    { wolof: "wër", francais: "tourner", anglais: "to turn" },
    { wolof: "dogg", francais: "entrer", anglais: "to enter" },
    { wolof: "daan", francais: "se lever", anglais: "to get up" },
    { wolof: "sëq", francais: "se coucher", anglais: "to lie down" },
    { wolof: "góor-góor", francais: "lentement", anglais: "slowly" },
    { wolof: "yéeg", francais: "rapide", anglais: "fast" },
    { wolof: "gudd", francais: "long", anglais: "long" },
    { wolof: "taw", francais: "court", anglais: "short" },
    { wolof: "weex", francais: "blanc", anglais: "white" },
    { wolof: "noon", francais: "noir", anglais: "black" },
    { wolof: "bun", francais: "rouge", anglais: "red" },
    { wolof: "baxa", francais: "vert", anglais: "green" },
    { wolof: "mboq", francais: "jaune", anglais: "yellow" },
    { wolof: "bulé", francais: "bleu", anglais: "blue" },
    { wolof: "xonq", francais: "marron", anglais: "brown" },
    { wolof: "xawa", francais: "gris", anglais: "gray" },
    { wolof: "baax", francais: "grand", anglais: "big" },
    { wolof: "tuuti", francais: "petit", anglais: "small" },
    { wolof: "dëgër", francais: "fort", anglais: "strong" },
    { wolof: "wóor", francais: "lourd", anglais: "heavy" },
    { wolof: "yomb", francais: "léger", anglais: "light" },
    { wolof: "seetsi", francais: "beau", anglais: "beautiful" },
    { wolof: "bon", francais: "mauvais", anglais: "bad" },
    { wolof: "baax", francais: "bon", anglais: "good" },
    { wolof: "xel", francais: "intelligent", anglais: "intelligent" },
    { wolof: "góor", francais: "courageux", anglais: "brave" },
    { wolof: "sago", francais: "malade", anglais: "sick" },
    { wolof: "wér", francais: "propre", anglais: "clean" },
    { wolof: "ndaw", francais: "sale", anglais: "dirty" },
    { wolof: "sori", francais: "chaud", anglais: "hot" },
    { wolof: "seetal", francais: "froid", anglais: "cold" },
    { wolof: "dara", francais: "rien", anglais: "nothing" },
    { wolof: "lépp", francais: "tout", anglais: "everything" },
    { wolof: "keneen", francais: "quelqu'un", anglais: "someone" },
    { wolof: "fan", francais: "où", anglais: "where" },
    { wolof: "kan", francais: "qui", anglais: "who" },
    { wolof: "lan", francais: "quoi", anglais: "what" },
    { wolof: "nga", francais: "tu", anglais: "you" },
    { wolof: "ma", francais: "je", anglais: "I" },
    { wolof: "mu", francais: "il/elle", anglais: "he/she" },
    { wolof: "ñun", francais: "nous", anglais: "we" },
    { wolof: "yéen", francais: "vous", anglais: "you (plural)" },
    { wolof: "ñu", francais: "ils/elles", anglais: "they" },
    { wolof: "sama", francais: "mon", anglais: "my" },
    { wolof: "sa", francais: "ton", anglais: "your" },
    { wolof: "samay", francais: "mes", anglais: "my (plural)" },
    { wolof: "say", francais: "tes", anglais: "your (plural)" },
    { wolof: "bi", francais: "le/la (défini)", anglais: "the" },
    { wolof: "yi", francais: "les (défini)", anglais: "the (plural)" },
    { wolof: "benn", francais: "un", anglais: "one" },
    { wolof: "ñaar", francais: "deux", anglais: "two" },
    { wolof: "nett", francais: "trois", anglais: "three" },
    { wolof: "ñeent", francais: "quatre", anglais: "four" },
    { wolof: "juróom", francais: "cinq", anglais: "five" },
    { wolof: "juróom-benn", francais: "six", anglais: "six" },
    { wolof: "juróom-ñaar", francais: "sept", anglais: "seven" },
    { wolof: "juróom-nett", francais: "huit", anglais: "eight" },
    { wolof: "juróom-ñeent", francais: "neuf", anglais: "nine" },
    { wolof: "fukk", francais: "dix", anglais: "ten" }
];
